apiVersion: v1
kind: ReplicationController
metadata:
  name: mynginx-rc
spec:
   replicas: 3
   selector: 
     app: myonlinestore
     
   template:
     metadata:
       labels:
          app: mynginx-rc
          
     spec:
        containers:
        - name: mynginx-container   
          image: nignx
          ports:
          - containerPort: 80 